# Generated by Django 4.0.5 on 2022-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNegocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email_cli',
            field=models.EmailField(default='2021/02/02', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='email_prov',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
